### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by justinmakaila** [Malpaux/apollo-offline#12]
For whatever reason, `redux-offline` isn't installed when I added this to my project...

(Truncated) `yarn list` output:
```
...
├─ apollo-link-core@0.5.0
│  ├─ graphql-tag@^2.4.2
│  ├─ graphql@^0.10.3
│  └─ zen-observable-ts@^0.4.0
├─ apollo-offline@0.0.7
├─ append-transform@0.4.0
│  └─ default-require-extensions@^1.0.0
├─ aproba@1.1.2
├─ are-we-there-yet@1.1.4
│  ├─ delegates@^1.0.0
│  └─ readable-stream@^2.0.6
...
```

**Comment by PaulBrachmann** [comment]
Hey @justinmakaila,
please take a look at the README's ["Install" section](https://github.com/Malpaux/apollo-offline#install). 

The following packages are **peer** dependencies:
- ```apollo-client``` (or any distribution including it, e.g. ```react-apollo```)
- ```redux```
- ```redux-offline```

They will not be installed automatically; adding them manually is required. This is a design decision that aims to give you more control over which specific versions of these you want to use in your project.

I hope this clears things up for you.

If you want to discuss this decision or the way it is communicated in the README, feel free to share your thoughts!

**Comment by justinmakaila** [comment]
Got it, thanks!
