### ISSUE TITLE
How to blacklist key(s) in the redux store?

### ISSUE THREAD

**Issue by 0xpatrickdev** [Malpaux/apollo-offline#15]
Thank you for making this great lib!

In the `redux-persist` [docs](https://github.com/rt2zz/redux-persist/tree/v4#persiststorestore-config-callback), there's an option to **blacklist** certain keys in the `persistStore(store, [config, callback])` function. 

How can this be achieved with this library? Overriding something in `redux-offline/lib/defaults`?
 Thanks in advance !

**Comment by PaulBrachmann** [comment]
As you've identified, ```apollo-offline``` uses ```redux-offline``` under the hood.

[Their documentation](https://github.com/redux-offline/redux-offline#change-how-state-is-saved-to-disk) describes how to configure the underlying ```redux-persist``` instance: You just have to set ```config.persistOptions``` (```config``` being your base configuration for ```redux-offline```, e.g. from ```redux-offline/lib/defaults```) to your custom ```redux-persist``` configuration (which may include a blacklist).

If you need some example code or if you have any additional questions or problems, feel free to leave a comment.

**Comment by 0xpatrickdev** [comment]
Ok thank you, that is helpful @MLPXBrachmann
